(()=>{
const excludes='script,style,noscript,nav,aside,footer,button,[role="navigation"],[role="toolbar"],.related-news,.related-posts,.related-articles,.article-related,.box-related,.box-comment,.comments,.comment-list,.advertisement,.ads,.social-share,.share-buttons,.breadcrumb,.newsletter,.article-meta,.byline,.social-counts,time,[data-testid="placementTracking"]';
function text(node){if(!node)return'';const clone=node.cloneNode(true);for(const el of clone.querySelectorAll(excludes))el.remove();for(const el of clone.querySelectorAll('p,h1,h2,h3,h4,li,blockquote,br'))el.append('\n');return globalThis.ContentCore.clean(clone.textContent)}
function date(value){const raw=String(value||'').trim();if(!raw||!/[0-9]{4}/.test(raw))return null;const timestamp=/^[0-9]{10}(?:[0-9]{3})?$/.test(raw)?Number(raw)*(raw.length===10?1000:1):Date.parse(raw);if(!Number.isFinite(timestamp)||timestamp>Date.now()+86400000||timestamp<Date.UTC(1990,0,1))return null;return new Date(timestamp).toISOString()}
function absolutePublished(node){const doc=node?.ownerDocument||node,host=doc?.location?.hostname?.replace(/^www\./,''),extra=globalThis.RemoteConfig?.get('adapters')?.[host]?.published||[];for(const selector of ['time[datetime]','[itemprop="datePublished"]','[data-published-at]',...extra]){let elements=[];try{elements=[...(node?.querySelectorAll(selector)||[])]}catch{}for(const el of elements){const result=date(el.getAttribute('datetime')||el.getAttribute('content')||el.getAttribute('data-published-at')||el.getAttribute('title')||el.textContent);if(result)return result}}return null}
function relative(value,now=Date.now()){const raw=String(value||'').replace(/\s+/g,' ').trim(),m=raw.match(/^(\d+)\s*(seconds?|secs?|minutes?|mins?|hours?|hrs?|days?|weeks?|giây|phút|giờ|ngày|tuần)\s*(?:ago|trước)$/i);if(!m)return null;const unit=m[2].toLowerCase(),factor=/^(second|sec|giây)/.test(unit)?1000:/^(minute|min|phút)/.test(unit)?60000:/^(hour|hr|giờ)/.test(unit)?3600000:/^(day|ngày)/.test(unit)?86400000:604800000;const timestamp=now-Number(m[1])*factor;if(!Number.isFinite(timestamp)||timestamp<Date.UTC(1990,0,1))return null;return{publishedAt:new Date(timestamp).toISOString(),publishedApproximate:true,publishedLabel:raw}}
function details(node){const exact=absolutePublished(node);if(exact)return{publishedAt:exact,publishedApproximate:false};for(const el of node?.querySelectorAll('time,span,small,div,p,strong,b')||[]){if(String(el.textContent).length>45)continue;const info=relative(el.textContent);if(info)return info}return{publishedAt:null}}
function nearby(node){let current=node;for(let depth=0;current&&depth<4;depth++,current=current.parentElement){if(current.querySelectorAll('a[href*="/research/"] [class*="font-bold"]').length>1)break;const info=details(current);if(info.publishedAt)return info}return{publishedAt:null}}
function published(node){return details(node).publishedAt}

function structured(doc){for(const script of doc.querySelectorAll('script[type="application/ld+json"]'))try{const raw=JSON.parse(script.textContent),items=Array.isArray(raw)?raw:raw['@graph']||[raw];for(const item of items)if(item&&(/Article|NewsArticle|BlogPosting/.test(String(item['@type']))||typeof item.articleBody==='string'))return{title:item.headline||'',text:item.articleBody||'',publishedAt:date(item.datePublished)}}catch{}return{}}
function sourceName(url){try{const host=new URL(url).hostname.replace(/^www\./,''),labels=globalThis.RemoteConfig?.get('general')?.sourceLabels||{};return labels[host]||({'sosovalue.com':'SoSoValue','dantri.com.vn':'Dân trí','tuoitre.vn':'Tuổi trẻ','manual.assistant.invalid':'Thủ công'})[host]||host}catch{return'Thủ công'}}
globalThis.ContentReader={text,published,details,nearby,relative,date,structured,sourceName};
})();
