(()=>{
const R=globalThis.ReplyLayout,names={generate:'Tạo gợi ý',regenerate:'Tạo lại gợi ý',style:'Phong cách trả lời',count:'Số lượng gợi ý',fast:'Gợi ý nhanh',settings:'Cài đặt',autoSuggest:'Tự động gợi ý',autoLike:'Tự động like',autoReply:'Tự động trả lời'};
const auto={autoSuggest:'Tạo khi mở bài',autoLike:'Like khi mở bài',autoReply:'Đăng khi chọn gợi ý'};
const paths={generate:'m12 2 1.8 5.5L19 9.5l-5.2 2L12 17l-1.8-5.5L5 9.5l5.2-2L12 2Z',regenerate:'M20 12a8 8 0 1 1-2.34-5.66M20 4v6h-6',fast:'m13 2-9 12h7l-1 8 10-12h-7l1-8Z',settings:'M12 3v3M12 18v3M3 12h3M18 12h3M5.6 5.6l2.1 2.1M16.3 16.3l2.1 2.1M18.4 5.6l-2.1 2.1M7.7 16.3l-2.1 2.1',autoSuggest:'M12 3v18M3 12h18M5.6 5.6l12.8 12.8M18.4 5.6 5.6 18.4',autoLike:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.9-8.6a5.5 5.5 0 0 0-.1-7.8Z',autoReply:'m22 2-7 20-4-9-9-4 20-7Z'};
let layout=R.normalize(),moving,opened=false;
const card=document.createElement('section');card.className='config-card reply-layout-settings';card.innerHTML='<h2>Giao diện trả lời</h2><p class="hint">Kéo thả để sắp xếp nút. Bấm biểu tượng Cài đặt để mở các mục tự động; có thể kéo chúng lên thanh công cụ hoặc đổi thứ tự trong Cài đặt.</p><div class="reply-layout-preview"><div class="reply-preview-editor">Đăng câu trả lời của bạn</div><div class="reply-preview-tools"><div data-side="left" aria-label="Bên trái"></div><div data-side="right" aria-label="Bên phải"></div></div><div class="reply-preview-auto" data-side="menu" aria-label="Cài đặt tự động" hidden></div><div class="reply-preview-suggestion"><span>Điểm đáng chú ý là công nghệ này đang tiến gần hơn tới nhu cầu thực tế của người dùng.</span><small>95%</small></div><div class="reply-preview-suggestion"><span>Ý tưởng hay, nhưng trải nghiệm sử dụng mới là điều quyết định nó có đi xa được không.</span><small>90%</small></div><small class="reply-preview-time">1,8 giây · Ví dụ mô phỏng</small></div><div class="reply-preview-hidden" data-side="hidden" aria-label="Các nút đã ẩn">Kéo nút vào đây để ẩn</div><p class="hint" id="replyLayoutStatus" role="status"></p>';
document.querySelector('[data-reply-preferences]').append(card);
const status=card.querySelector('#replyLayoutStatus');
async function save(){layout=R.normalize(layout);render();try{await chrome.storage.local.set({replyLayout:layout});status.textContent='Đã áp dụng giao diện trả lời.'}catch{status.textContent='Không lưu được. Hãy mở lại bảng cài đặt.'}}
function move(id,side,index){if(!R.ids.includes(id)||!['left','right','hidden','menu'].includes(side)||side==='menu'&&!auto[id])return;for(const key of ['left','right','hidden','menu'])layout[key]=layout[key].filter(value=>value!==id);layout[side].splice(index??layout[side].length,0,id);save()}
function draggable(node,id,side){node.draggable=true;node.dataset.control=id;node.title=names[id]+' · Kéo để di chuyển';node.ondragstart=e=>{moving=id;e.dataTransfer.setData('text/plain',id);e.dataTransfer.effectAllowed='move'};node.ondragend=()=>{moving=null};node.ondragover=e=>e.preventDefault();node.ondrop=e=>{e.preventDefault();e.stopPropagation();const from=e.dataTransfer.getData('text/plain')||moving;if(from===id)return;move(from,side,layout[side].filter(value=>value!==from).indexOf(id))};return node}
function button(id,side){const b=document.createElement('button');b.type='button';b.className='reply-preview-button';b.setAttribute('aria-label',names[id]);if(paths[id]){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',paths[id]);svg.append(path);if(id==='settings'){const c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.setAttribute('cx','12');c.setAttribute('cy','12');c.setAttribute('r','6');svg.append(c)}b.append(svg)}else b.textContent=id==='style'?'Mặc định ▾':'2';if(id==='settings'){b.setAttribute('aria-expanded',String(opened));b.onclick=()=>{opened=!opened;render()}}if(auto[id])b.classList.add('active');return draggable(b,id,side)}
function render(){for(const side of ['left','right','menu','hidden']){const group=card.querySelector(`[data-side="${side}"]`);group.replaceChildren(...layout[side].map(id=>{if(side!=='menu')return button(id,side);const row=document.createElement('label');row.className='reply-preview-auto-row';const text=document.createElement('span'),title=document.createElement('b'),hint=document.createElement('small'),check=document.createElement('input');title.textContent=names[id];hint.textContent=auto[id];check.type='checkbox';check.checked=true;check.setAttribute('aria-label',names[id]+' (simulation)');text.append(title,hint);row.append(text,check);return draggable(row,id,side)}));if(side==='hidden'&&!layout.hidden.length)group.textContent='Kéo nút vào đây để ẩn';if(side==='menu')group.hidden=!opened;group.ondragover=e=>{e.preventDefault();group.classList.add('drag-over')};group.ondragleave=()=>group.classList.remove('drag-over');group.ondrop=e=>{e.preventDefault();group.classList.remove('drag-over');move(e.dataTransfer.getData('text/plain')||moving,side)}}}
chrome.storage.local.get('replyLayout').then(s=>{layout=R.normalize(s.replyLayout);render()});chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes.replyLayout){layout=R.normalize(changes.replyLayout.newValue);render()}});
chrome.storage.local.remove('hideDiscovery').catch(()=>{});
})();
