(()=>{
if(globalThis.RemoteConfig)return;
const BASE='https://raw.githubusercontent.com/TO-HU-TIEU/configs/main/',PATHS={general:'settings/general.json',limits:'settings/limits.json',endpoints:'settings/endpoints.json',content:'prompts/content.json',reply:'prompts/reply.json',styles:'presets/reply-styles.json',contentStyles:'presets/content-styles.json',adapters:'sources/adapters.json'};
let cache=null,inflight;
const defaults={general:{sourceLabels:{'sosovalue.com':'SoSoValue','dantri.com.vn':'Dân trí','tuoitre.vn':'Tuổi trẻ'}},limits:{maxSources:20,maxArticles:120,maxQueue:120,maxSourceCharacters:10000,minSourceCharacters:80},endpoints:{presets:BASE+PATHS.styles},content:{supplement:''},reply:{supplement:''},styles:{version:1,styles:[]},contentStyles:globalThis.ContentPresets||{version:1,styles:[]},adapters:{}};
function validate(key,value){if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Cấu hình không hợp lệ: '+key);if(key==='limits')for(const[k,min,max]of [['maxSources',1,20],['maxArticles',20,120],['maxQueue',1,120],['maxSourceCharacters',1000,10000],['minSourceCharacters',40,200]])if(!Number.isInteger(value[k])||value[k]<min||value[k]>max)throw new Error('Giới hạn không hợp lệ');if(['content','reply'].includes(key)&&(!value.supplement||typeof value.supplement!=='string'||value.supplement.length>12000))throw new Error('Prompt không hợp lệ');if(['styles','contentStyles'].includes(key)&&(!Array.isArray(value.styles)||!value.styles.length||value.styles.length>30||!value.styles.every(s=>s&&typeof s.id==='string'&&typeof s.name==='string'&&s.name.length<=80&&typeof s.prompt==='string'&&s.prompt.length<=6000)))throw new Error('Preset không hợp lệ');if(key==='contentStyles'&&(value.styles.length!==2||value.styles.some(s=>!s.id||!s.prompt)))throw new Error('Content preset không hợp lệ');if(key==='endpoints'&&value.presets!==BASE+PATHS.styles)throw new Error('Endpoint không được phép');if(key==='general'&&(!value.sourceLabels||Object.values(value.sourceLabels).some(label=>typeof label!=='string'||label.length>80)))throw new Error('Tên nguồn không hợp lệ');if(key==='adapters')for(const[host,adapter]of Object.entries(value)){if(!/^[a-z0-9.-]+$/.test(host)||!Array.isArray(adapter.body)||adapter.body.length>12||adapter.body.some(s=>typeof s!=='string'||s.length>200)||(adapter.feed&&(!Array.isArray(adapter.feed)||adapter.feed.length>12||adapter.feed.some(s=>typeof s!=='string'||s.length>200)))||(adapter.published&&(!Array.isArray(adapter.published)||adapter.published.length>12||adapter.published.some(s=>typeof s!=='string'||s.length>200))))throw new Error('Adapter không hợp lệ')}return value}
function storage(){try{return globalThis.chrome?.storage?.local}catch{return null}}
const ready=Promise.resolve().then(()=>storage()?.get('sharedConfigCache')||{}).then(({sharedConfigCache})=>{try{if(sharedConfigCache?.data){for(const[key,value]of Object.entries(sharedConfigCache.data))validate(key,value);if(Object.keys(PATHS).every(key=>sharedConfigCache.data[key]))cache=sharedConfigCache}}catch{}return cache}).catch(()=>null);
async function refresh(force=false){await ready;if(!storage())return cache;if(inflight)return inflight;if(!force&&cache&&Date.now()-cache.checkedAt<3600000)return cache;inflight=(async()=>{try{const options={cache:'no-store',signal:globalThis.AbortSignal?.timeout(12000)},response=await fetch(BASE+'manifest.json',options);if(!response.ok)throw new Error('Không tải được manifest');const manifest=await response.json();if(manifest.schemaVersion!==1||typeof manifest.version!=='string'||!manifest.resources)throw new Error('Manifest không hợp lệ');if(cache?.version===manifest.version){cache={...cache,checkedAt:Date.now()};await storage()?.set({sharedConfigCache:cache});return cache}const data={};await Promise.all(Object.entries(PATHS).map(async([key,path])=>{const resource=manifest.resources[key];if(resource?.path!==path||!/^\w{64}$/.test(resource.sha256))throw new Error('Tài nguyên không hợp lệ');const r=await fetch(BASE+path,options);if(!r.ok)throw new Error('Không tải được cấu hình');const raw=await r.text();if(raw.length>250000)throw new Error('Tài nguyên quá lớn');const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw))),b=>b.toString(16).padStart(2,'0')).join('');if(hash!==resource.sha256)throw new Error('Cấu hình đang cập nhật');data[key]=validate(key,JSON.parse(raw))}));cache={version:manifest.version,checkedAt:Date.now(),data};const personal=await storage()?.get('customStyles')||{};await storage()?.set({sharedConfigCache:cache,replyStyleCatalog:[...data.styles.styles,...(personal.customStyles||[])],remotePresetCache:data.styles});return cache}catch{return cache}})().finally(()=>{inflight=null});return inflight}
function start(){if(!storage())return;refresh().catch(()=>{});chrome.alarms?.create('shared-config-refresh',{periodInMinutes:60});chrome.alarms?.onAlarm.addListener(alarm=>{if(alarm.name==='shared-config-refresh')refresh(true).catch(()=>{})});chrome.runtime.onInstalled?.addListener(()=>refresh(true));chrome.runtime.onStartup?.addListener(()=>refresh())}
try{globalThis.chrome?.storage?.onChanged?.addListener((changes,area)=>{if(area==='local'&&changes.sharedConfigCache)cache=changes.sharedConfigCache.newValue||cache})}catch{/* Extension reload can revoke APIs on an old page. */}
globalThis.RemoteConfig={ready,refresh,start,get:key=>cache?.data?.[key]||defaults[key],version:()=>cache?.version||'bundled'};
})();
